// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Partition_PartitionBrokerRole int32

const (
	Partition_LEADER   Partition_PartitionBrokerRole = 0
	Partition_FOLLOWER Partition_PartitionBrokerRole = 1
)

var Partition_PartitionBrokerRole_name = map[int32]string{
	0: "LEADER",
	1: "FOLLOWER",
}

var Partition_PartitionBrokerRole_value = map[string]int32{
	"LEADER":   0,
	"FOLLOWER": 1,
}

func (x Partition_PartitionBrokerRole) String() string {
	return proto.EnumName(Partition_PartitionBrokerRole_name, int32(x))
}

func (Partition_PartitionBrokerRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1, 0}
}

type WorkflowRequestObject_ResourceType int32

const (
	// FILE type means the gateway will try to detect the resource type using the file extension of the name
	WorkflowRequestObject_FILE WorkflowRequestObject_ResourceType = 0
	WorkflowRequestObject_BPMN WorkflowRequestObject_ResourceType = 1
	WorkflowRequestObject_YAML WorkflowRequestObject_ResourceType = 2
)

var WorkflowRequestObject_ResourceType_name = map[int32]string{
	0: "FILE",
	1: "BPMN",
	2: "YAML",
}

var WorkflowRequestObject_ResourceType_value = map[string]int32{
	"FILE": 0,
	"BPMN": 1,
	"YAML": 2,
}

func (x WorkflowRequestObject_ResourceType) String() string {
	return proto.EnumName(WorkflowRequestObject_ResourceType_name, int32(x))
}

func (WorkflowRequestObject_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4, 0}
}

type TopologyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopologyRequest) Reset()         { *m = TopologyRequest{} }
func (m *TopologyRequest) String() string { return proto.CompactTextString(m) }
func (*TopologyRequest) ProtoMessage()    {}
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *TopologyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyRequest.Unmarshal(m, b)
}
func (m *TopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyRequest.Marshal(b, m, deterministic)
}
func (m *TopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyRequest.Merge(m, src)
}
func (m *TopologyRequest) XXX_Size() int {
	return xxx_messageInfo_TopologyRequest.Size(m)
}
func (m *TopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyRequest proto.InternalMessageInfo

type Partition struct {
	PartitionId          int32                         `protobuf:"varint,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Role                 Partition_PartitionBrokerRole `protobuf:"varint,3,opt,name=role,proto3,enum=gateway_protocol.Partition_PartitionBrokerRole" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *Partition) GetRole() Partition_PartitionBrokerRole {
	if m != nil {
		return m.Role
	}
	return Partition_LEADER
}

type BrokerInfo struct {
	NodeId               int32        `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Host                 string       `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32        `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Partitions           []*Partition `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BrokerInfo) Reset()         { *m = BrokerInfo{} }
func (m *BrokerInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerInfo) ProtoMessage()    {}
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *BrokerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerInfo.Unmarshal(m, b)
}
func (m *BrokerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerInfo.Marshal(b, m, deterministic)
}
func (m *BrokerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerInfo.Merge(m, src)
}
func (m *BrokerInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerInfo.Size(m)
}
func (m *BrokerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerInfo proto.InternalMessageInfo

func (m *BrokerInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *BrokerInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BrokerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *BrokerInfo) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type TopologyResponse struct {
	Brokers              []*BrokerInfo `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	ClusterSize          int32         `protobuf:"varint,2,opt,name=clusterSize,proto3" json:"clusterSize,omitempty"`
	PartitionsCount      int32         `protobuf:"varint,3,opt,name=partitionsCount,proto3" json:"partitionsCount,omitempty"`
	ReplicationFactor    int32         `protobuf:"varint,4,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TopologyResponse) Reset()         { *m = TopologyResponse{} }
func (m *TopologyResponse) String() string { return proto.CompactTextString(m) }
func (*TopologyResponse) ProtoMessage()    {}
func (*TopologyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *TopologyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyResponse.Unmarshal(m, b)
}
func (m *TopologyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyResponse.Marshal(b, m, deterministic)
}
func (m *TopologyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyResponse.Merge(m, src)
}
func (m *TopologyResponse) XXX_Size() int {
	return xxx_messageInfo_TopologyResponse.Size(m)
}
func (m *TopologyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyResponse proto.InternalMessageInfo

func (m *TopologyResponse) GetBrokers() []*BrokerInfo {
	if m != nil {
		return m.Brokers
	}
	return nil
}

func (m *TopologyResponse) GetClusterSize() int32 {
	if m != nil {
		return m.ClusterSize
	}
	return 0
}

func (m *TopologyResponse) GetPartitionsCount() int32 {
	if m != nil {
		return m.PartitionsCount
	}
	return 0
}

func (m *TopologyResponse) GetReplicationFactor() int32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

type WorkflowRequestObject struct {
	Name                 string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 WorkflowRequestObject_ResourceType `protobuf:"varint,2,opt,name=type,proto3,enum=gateway_protocol.WorkflowRequestObject_ResourceType" json:"type,omitempty"`
	Definition           []byte                             `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *WorkflowRequestObject) Reset()         { *m = WorkflowRequestObject{} }
func (m *WorkflowRequestObject) String() string { return proto.CompactTextString(m) }
func (*WorkflowRequestObject) ProtoMessage()    {}
func (*WorkflowRequestObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4}
}

func (m *WorkflowRequestObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowRequestObject.Unmarshal(m, b)
}
func (m *WorkflowRequestObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowRequestObject.Marshal(b, m, deterministic)
}
func (m *WorkflowRequestObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowRequestObject.Merge(m, src)
}
func (m *WorkflowRequestObject) XXX_Size() int {
	return xxx_messageInfo_WorkflowRequestObject.Size(m)
}
func (m *WorkflowRequestObject) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowRequestObject.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowRequestObject proto.InternalMessageInfo

func (m *WorkflowRequestObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowRequestObject) GetType() WorkflowRequestObject_ResourceType {
	if m != nil {
		return m.Type
	}
	return WorkflowRequestObject_FILE
}

func (m *WorkflowRequestObject) GetDefinition() []byte {
	if m != nil {
		return m.Definition
	}
	return nil
}

type DeployWorkflowRequest struct {
	Workflows            []*WorkflowRequestObject `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DeployWorkflowRequest) Reset()         { *m = DeployWorkflowRequest{} }
func (m *DeployWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*DeployWorkflowRequest) ProtoMessage()    {}
func (*DeployWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{5}
}

func (m *DeployWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployWorkflowRequest.Unmarshal(m, b)
}
func (m *DeployWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *DeployWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployWorkflowRequest.Merge(m, src)
}
func (m *DeployWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_DeployWorkflowRequest.Size(m)
}
func (m *DeployWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployWorkflowRequest proto.InternalMessageInfo

func (m *DeployWorkflowRequest) GetWorkflows() []*WorkflowRequestObject {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type WorkflowMetadata struct {
	BpmnProcessId        string   `protobuf:"bytes,1,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowKey          int64    `protobuf:"varint,3,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	ResourceName         string   `protobuf:"bytes,4,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowMetadata) Reset()         { *m = WorkflowMetadata{} }
func (m *WorkflowMetadata) String() string { return proto.CompactTextString(m) }
func (*WorkflowMetadata) ProtoMessage()    {}
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{6}
}

func (m *WorkflowMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowMetadata.Unmarshal(m, b)
}
func (m *WorkflowMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowMetadata.Marshal(b, m, deterministic)
}
func (m *WorkflowMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowMetadata.Merge(m, src)
}
func (m *WorkflowMetadata) XXX_Size() int {
	return xxx_messageInfo_WorkflowMetadata.Size(m)
}
func (m *WorkflowMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowMetadata proto.InternalMessageInfo

func (m *WorkflowMetadata) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *WorkflowMetadata) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkflowMetadata) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *WorkflowMetadata) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type DeployWorkflowResponse struct {
	Key                  int64               `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Workflows            []*WorkflowMetadata `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeployWorkflowResponse) Reset()         { *m = DeployWorkflowResponse{} }
func (m *DeployWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*DeployWorkflowResponse) ProtoMessage()    {}
func (*DeployWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{7}
}

func (m *DeployWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployWorkflowResponse.Unmarshal(m, b)
}
func (m *DeployWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployWorkflowResponse.Marshal(b, m, deterministic)
}
func (m *DeployWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployWorkflowResponse.Merge(m, src)
}
func (m *DeployWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_DeployWorkflowResponse.Size(m)
}
func (m *DeployWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployWorkflowResponse proto.InternalMessageInfo

func (m *DeployWorkflowResponse) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *DeployWorkflowResponse) GetWorkflows() []*WorkflowMetadata {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type PublishMessageRequest struct {
	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CorrelationKey string `protobuf:"bytes,2,opt,name=correlationKey,proto3" json:"correlationKey,omitempty"`
	TimeToLive     int64  `protobuf:"varint,3,opt,name=timeToLive,proto3" json:"timeToLive,omitempty"`
	MessageId      string `protobuf:"bytes,4,opt,name=messageId,proto3" json:"messageId,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMessageRequest) Reset()         { *m = PublishMessageRequest{} }
func (m *PublishMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PublishMessageRequest) ProtoMessage()    {}
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{8}
}

func (m *PublishMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMessageRequest.Unmarshal(m, b)
}
func (m *PublishMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMessageRequest.Marshal(b, m, deterministic)
}
func (m *PublishMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMessageRequest.Merge(m, src)
}
func (m *PublishMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PublishMessageRequest.Size(m)
}
func (m *PublishMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMessageRequest proto.InternalMessageInfo

func (m *PublishMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishMessageRequest) GetCorrelationKey() string {
	if m != nil {
		return m.CorrelationKey
	}
	return ""
}

func (m *PublishMessageRequest) GetTimeToLive() int64 {
	if m != nil {
		return m.TimeToLive
	}
	return 0
}

func (m *PublishMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *PublishMessageRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type PublishMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMessageResponse) Reset()         { *m = PublishMessageResponse{} }
func (m *PublishMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PublishMessageResponse) ProtoMessage()    {}
func (*PublishMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{9}
}

func (m *PublishMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMessageResponse.Unmarshal(m, b)
}
func (m *PublishMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMessageResponse.Marshal(b, m, deterministic)
}
func (m *PublishMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMessageResponse.Merge(m, src)
}
func (m *PublishMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PublishMessageResponse.Size(m)
}
func (m *PublishMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMessageResponse proto.InternalMessageInfo

type CreateJobRequest struct {
	JobType string `protobuf:"bytes,1,opt,name=jobType,proto3" json:"jobType,omitempty"`
	Retries int32  `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	// custom headers has to be a valid json object as string
	CustomHeaders string `protobuf:"bytes,3,opt,name=customHeaders,proto3" json:"customHeaders,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{10}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetJobType() string {
	if m != nil {
		return m.JobType
	}
	return ""
}

func (m *CreateJobRequest) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *CreateJobRequest) GetCustomHeaders() string {
	if m != nil {
		return m.CustomHeaders
	}
	return ""
}

func (m *CreateJobRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CreateJobResponse struct {
	Key                  int64    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{11}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type UpdateJobRetriesRequest struct {
	JobKey               int64    `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	Retries              int32    `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRetriesRequest) Reset()         { *m = UpdateJobRetriesRequest{} }
func (m *UpdateJobRetriesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRetriesRequest) ProtoMessage()    {}
func (*UpdateJobRetriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{12}
}

func (m *UpdateJobRetriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRetriesRequest.Unmarshal(m, b)
}
func (m *UpdateJobRetriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRetriesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateJobRetriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRetriesRequest.Merge(m, src)
}
func (m *UpdateJobRetriesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRetriesRequest.Size(m)
}
func (m *UpdateJobRetriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRetriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRetriesRequest proto.InternalMessageInfo

func (m *UpdateJobRetriesRequest) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *UpdateJobRetriesRequest) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

type UpdateJobRetriesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRetriesResponse) Reset()         { *m = UpdateJobRetriesResponse{} }
func (m *UpdateJobRetriesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRetriesResponse) ProtoMessage()    {}
func (*UpdateJobRetriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{13}
}

func (m *UpdateJobRetriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRetriesResponse.Unmarshal(m, b)
}
func (m *UpdateJobRetriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRetriesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateJobRetriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRetriesResponse.Merge(m, src)
}
func (m *UpdateJobRetriesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRetriesResponse.Size(m)
}
func (m *UpdateJobRetriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRetriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRetriesResponse proto.InternalMessageInfo

type FailJobRequest struct {
	JobKey               int64    `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	Retries              int32    `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailJobRequest) Reset()         { *m = FailJobRequest{} }
func (m *FailJobRequest) String() string { return proto.CompactTextString(m) }
func (*FailJobRequest) ProtoMessage()    {}
func (*FailJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{14}
}

func (m *FailJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailJobRequest.Unmarshal(m, b)
}
func (m *FailJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailJobRequest.Marshal(b, m, deterministic)
}
func (m *FailJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailJobRequest.Merge(m, src)
}
func (m *FailJobRequest) XXX_Size() int {
	return xxx_messageInfo_FailJobRequest.Size(m)
}
func (m *FailJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FailJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FailJobRequest proto.InternalMessageInfo

func (m *FailJobRequest) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *FailJobRequest) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

type FailJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailJobResponse) Reset()         { *m = FailJobResponse{} }
func (m *FailJobResponse) String() string { return proto.CompactTextString(m) }
func (*FailJobResponse) ProtoMessage()    {}
func (*FailJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{15}
}

func (m *FailJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailJobResponse.Unmarshal(m, b)
}
func (m *FailJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailJobResponse.Marshal(b, m, deterministic)
}
func (m *FailJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailJobResponse.Merge(m, src)
}
func (m *FailJobResponse) XXX_Size() int {
	return xxx_messageInfo_FailJobResponse.Size(m)
}
func (m *FailJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FailJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FailJobResponse proto.InternalMessageInfo

type CompleteJobRequest struct {
	JobKey int64 `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteJobRequest) Reset()         { *m = CompleteJobRequest{} }
func (m *CompleteJobRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteJobRequest) ProtoMessage()    {}
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{16}
}

func (m *CompleteJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteJobRequest.Unmarshal(m, b)
}
func (m *CompleteJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteJobRequest.Marshal(b, m, deterministic)
}
func (m *CompleteJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteJobRequest.Merge(m, src)
}
func (m *CompleteJobRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteJobRequest.Size(m)
}
func (m *CompleteJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteJobRequest proto.InternalMessageInfo

func (m *CompleteJobRequest) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *CompleteJobRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CompleteJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteJobResponse) Reset()         { *m = CompleteJobResponse{} }
func (m *CompleteJobResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteJobResponse) ProtoMessage()    {}
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{17}
}

func (m *CompleteJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteJobResponse.Unmarshal(m, b)
}
func (m *CompleteJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteJobResponse.Marshal(b, m, deterministic)
}
func (m *CompleteJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteJobResponse.Merge(m, src)
}
func (m *CompleteJobResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteJobResponse.Size(m)
}
func (m *CompleteJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteJobResponse proto.InternalMessageInfo

type CreateWorkflowInstanceRequest struct {
	WorkflowKey   int64  `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	BpmnProcessId string `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	// if bpmnProcessId is set version = -1 indicates to use the latest version
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWorkflowInstanceRequest) Reset()         { *m = CreateWorkflowInstanceRequest{} }
func (m *CreateWorkflowInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWorkflowInstanceRequest) ProtoMessage()    {}
func (*CreateWorkflowInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{18}
}

func (m *CreateWorkflowInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkflowInstanceRequest.Unmarshal(m, b)
}
func (m *CreateWorkflowInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkflowInstanceRequest.Marshal(b, m, deterministic)
}
func (m *CreateWorkflowInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkflowInstanceRequest.Merge(m, src)
}
func (m *CreateWorkflowInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWorkflowInstanceRequest.Size(m)
}
func (m *CreateWorkflowInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkflowInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkflowInstanceRequest proto.InternalMessageInfo

func (m *CreateWorkflowInstanceRequest) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *CreateWorkflowInstanceRequest) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *CreateWorkflowInstanceRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CreateWorkflowInstanceRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CreateWorkflowInstanceResponse struct {
	WorkflowKey          int64    `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	BpmnProcessId        string   `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowInstanceKey  int64    `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWorkflowInstanceResponse) Reset()         { *m = CreateWorkflowInstanceResponse{} }
func (m *CreateWorkflowInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateWorkflowInstanceResponse) ProtoMessage()    {}
func (*CreateWorkflowInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{19}
}

func (m *CreateWorkflowInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkflowInstanceResponse.Unmarshal(m, b)
}
func (m *CreateWorkflowInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkflowInstanceResponse.Marshal(b, m, deterministic)
}
func (m *CreateWorkflowInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkflowInstanceResponse.Merge(m, src)
}
func (m *CreateWorkflowInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateWorkflowInstanceResponse.Size(m)
}
func (m *CreateWorkflowInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkflowInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkflowInstanceResponse proto.InternalMessageInfo

func (m *CreateWorkflowInstanceResponse) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *CreateWorkflowInstanceResponse) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *CreateWorkflowInstanceResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CreateWorkflowInstanceResponse) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

type CancelWorkflowInstanceRequest struct {
	WorkflowInstanceKey  int64    `protobuf:"varint,1,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelWorkflowInstanceRequest) Reset()         { *m = CancelWorkflowInstanceRequest{} }
func (m *CancelWorkflowInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*CancelWorkflowInstanceRequest) ProtoMessage()    {}
func (*CancelWorkflowInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{20}
}

func (m *CancelWorkflowInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelWorkflowInstanceRequest.Unmarshal(m, b)
}
func (m *CancelWorkflowInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelWorkflowInstanceRequest.Marshal(b, m, deterministic)
}
func (m *CancelWorkflowInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelWorkflowInstanceRequest.Merge(m, src)
}
func (m *CancelWorkflowInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_CancelWorkflowInstanceRequest.Size(m)
}
func (m *CancelWorkflowInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelWorkflowInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelWorkflowInstanceRequest proto.InternalMessageInfo

func (m *CancelWorkflowInstanceRequest) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

type CancelWorkflowInstanceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelWorkflowInstanceResponse) Reset()         { *m = CancelWorkflowInstanceResponse{} }
func (m *CancelWorkflowInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*CancelWorkflowInstanceResponse) ProtoMessage()    {}
func (*CancelWorkflowInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{21}
}

func (m *CancelWorkflowInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelWorkflowInstanceResponse.Unmarshal(m, b)
}
func (m *CancelWorkflowInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelWorkflowInstanceResponse.Marshal(b, m, deterministic)
}
func (m *CancelWorkflowInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelWorkflowInstanceResponse.Merge(m, src)
}
func (m *CancelWorkflowInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_CancelWorkflowInstanceResponse.Size(m)
}
func (m *CancelWorkflowInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelWorkflowInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelWorkflowInstanceResponse proto.InternalMessageInfo

type UpdateWorkflowInstancePayloadRequest struct {
	ElementInstanceKey int64 `protobuf:"varint,1,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWorkflowInstancePayloadRequest) Reset()         { *m = UpdateWorkflowInstancePayloadRequest{} }
func (m *UpdateWorkflowInstancePayloadRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateWorkflowInstancePayloadRequest) ProtoMessage()    {}
func (*UpdateWorkflowInstancePayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{22}
}

func (m *UpdateWorkflowInstancePayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Unmarshal(m, b)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Marshal(b, m, deterministic)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Merge(m, src)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Size(m)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWorkflowInstancePayloadRequest proto.InternalMessageInfo

func (m *UpdateWorkflowInstancePayloadRequest) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

func (m *UpdateWorkflowInstancePayloadRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type UpdateWorkflowInstancePayloadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWorkflowInstancePayloadResponse) Reset()         { *m = UpdateWorkflowInstancePayloadResponse{} }
func (m *UpdateWorkflowInstancePayloadResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateWorkflowInstancePayloadResponse) ProtoMessage()    {}
func (*UpdateWorkflowInstancePayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{23}
}

func (m *UpdateWorkflowInstancePayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Unmarshal(m, b)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Marshal(b, m, deterministic)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Merge(m, src)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Size(m)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWorkflowInstancePayloadResponse proto.InternalMessageInfo

type ListWorkflowsRequest struct {
	// optional filter by BPMN process id, if empty all workflows are returned
	BpmnProcessId        string   `protobuf:"bytes,1,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWorkflowsRequest) Reset()         { *m = ListWorkflowsRequest{} }
func (m *ListWorkflowsRequest) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowsRequest) ProtoMessage()    {}
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{24}
}

func (m *ListWorkflowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowsRequest.Unmarshal(m, b)
}
func (m *ListWorkflowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowsRequest.Marshal(b, m, deterministic)
}
func (m *ListWorkflowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowsRequest.Merge(m, src)
}
func (m *ListWorkflowsRequest) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowsRequest.Size(m)
}
func (m *ListWorkflowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowsRequest proto.InternalMessageInfo

func (m *ListWorkflowsRequest) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

type ListWorkflowsResponse struct {
	Workflows            []*WorkflowMetadata `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListWorkflowsResponse) Reset()         { *m = ListWorkflowsResponse{} }
func (m *ListWorkflowsResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowsResponse) ProtoMessage()    {}
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{25}
}

func (m *ListWorkflowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowsResponse.Unmarshal(m, b)
}
func (m *ListWorkflowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowsResponse.Marshal(b, m, deterministic)
}
func (m *ListWorkflowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowsResponse.Merge(m, src)
}
func (m *ListWorkflowsResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowsResponse.Size(m)
}
func (m *ListWorkflowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowsResponse proto.InternalMessageInfo

func (m *ListWorkflowsResponse) GetWorkflows() []*WorkflowMetadata {
	if m != nil {
		return m.Workflows
	}
	return nil
}

// either workflow key or bpmn process id and version has to be specified
type GetWorkflowRequest struct {
	WorkflowKey int64 `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	// if bpmnProcessId is set version = -1 indicates to use the latest version
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BpmnProcessId        string   `protobuf:"bytes,3,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowRequest) Reset()         { *m = GetWorkflowRequest{} }
func (m *GetWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowRequest) ProtoMessage()    {}
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{26}
}

func (m *GetWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowRequest.Unmarshal(m, b)
}
func (m *GetWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *GetWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowRequest.Merge(m, src)
}
func (m *GetWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowRequest.Size(m)
}
func (m *GetWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowRequest proto.InternalMessageInfo

func (m *GetWorkflowRequest) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *GetWorkflowRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetWorkflowRequest) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

type GetWorkflowResponse struct {
	WorkflowKey          int64    `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BpmnProcessId        string   `protobuf:"bytes,3,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	ResourceName         string   `protobuf:"bytes,4,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	BpmnXml              string   `protobuf:"bytes,5,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowResponse) Reset()         { *m = GetWorkflowResponse{} }
func (m *GetWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowResponse) ProtoMessage()    {}
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{27}
}

func (m *GetWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowResponse.Unmarshal(m, b)
}
func (m *GetWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowResponse.Marshal(b, m, deterministic)
}
func (m *GetWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowResponse.Merge(m, src)
}
func (m *GetWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowResponse.Size(m)
}
func (m *GetWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowResponse proto.InternalMessageInfo

func (m *GetWorkflowResponse) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *GetWorkflowResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetWorkflowResponse) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *GetWorkflowResponse) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *GetWorkflowResponse) GetBpmnXml() string {
	if m != nil {
		return m.BpmnXml
	}
	return ""
}

type ActivateJobsRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Worker               string   `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Variables            []string `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateJobsRequest) Reset()         { *m = ActivateJobsRequest{} }
func (m *ActivateJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateJobsRequest) ProtoMessage()    {}
func (*ActivateJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{28}
}

func (m *ActivateJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateJobsRequest.Unmarshal(m, b)
}
func (m *ActivateJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateJobsRequest.Marshal(b, m, deterministic)
}
func (m *ActivateJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateJobsRequest.Merge(m, src)
}
func (m *ActivateJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateJobsRequest.Size(m)
}
func (m *ActivateJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateJobsRequest proto.InternalMessageInfo

func (m *ActivateJobsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ActivateJobsRequest) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *ActivateJobsRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *ActivateJobsRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ActivateJobsRequest) GetVariables() []string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type JobHeaders struct {
	WorkflowInstanceKey       int64    `protobuf:"varint,1,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	BpmnProcessId             string   `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	WorkflowDefinitionVersion int32    `protobuf:"varint,3,opt,name=workflowDefinitionVersion,proto3" json:"workflowDefinitionVersion,omitempty"`
	WorkflowKey               int64    `protobuf:"varint,4,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	ElementId                 string   `protobuf:"bytes,5,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementInstanceKey        int64    `protobuf:"varint,6,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *JobHeaders) Reset()         { *m = JobHeaders{} }
func (m *JobHeaders) String() string { return proto.CompactTextString(m) }
func (*JobHeaders) ProtoMessage()    {}
func (*JobHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{29}
}

func (m *JobHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobHeaders.Unmarshal(m, b)
}
func (m *JobHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobHeaders.Marshal(b, m, deterministic)
}
func (m *JobHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobHeaders.Merge(m, src)
}
func (m *JobHeaders) XXX_Size() int {
	return xxx_messageInfo_JobHeaders.Size(m)
}
func (m *JobHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_JobHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_JobHeaders proto.InternalMessageInfo

func (m *JobHeaders) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *JobHeaders) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *JobHeaders) GetWorkflowDefinitionVersion() int32 {
	if m != nil {
		return m.WorkflowDefinitionVersion
	}
	return 0
}

func (m *JobHeaders) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *JobHeaders) GetElementId() string {
	if m != nil {
		return m.ElementId
	}
	return ""
}

func (m *JobHeaders) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

type ActivatedJob struct {
	Key        int64       `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Type       string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	JobHeaders *JobHeaders `protobuf:"bytes,3,opt,name=jobHeaders,proto3" json:"jobHeaders,omitempty"`
	// json object as string
	CustomHeaders string `protobuf:"bytes,4,opt,name=customHeaders,proto3" json:"customHeaders,omitempty"`
	Worker        string `protobuf:"bytes,5,opt,name=worker,proto3" json:"worker,omitempty"`
	Retries       int32  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	// epoch milliseconds
	Deadline int64 `protobuf:"varint,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// json object as string
	Payload              string   `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivatedJob) Reset()         { *m = ActivatedJob{} }
func (m *ActivatedJob) String() string { return proto.CompactTextString(m) }
func (*ActivatedJob) ProtoMessage()    {}
func (*ActivatedJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{30}
}

func (m *ActivatedJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivatedJob.Unmarshal(m, b)
}
func (m *ActivatedJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivatedJob.Marshal(b, m, deterministic)
}
func (m *ActivatedJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivatedJob.Merge(m, src)
}
func (m *ActivatedJob) XXX_Size() int {
	return xxx_messageInfo_ActivatedJob.Size(m)
}
func (m *ActivatedJob) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivatedJob.DiscardUnknown(m)
}

var xxx_messageInfo_ActivatedJob proto.InternalMessageInfo

func (m *ActivatedJob) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ActivatedJob) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ActivatedJob) GetJobHeaders() *JobHeaders {
	if m != nil {
		return m.JobHeaders
	}
	return nil
}

func (m *ActivatedJob) GetCustomHeaders() string {
	if m != nil {
		return m.CustomHeaders
	}
	return ""
}

func (m *ActivatedJob) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *ActivatedJob) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *ActivatedJob) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *ActivatedJob) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type ActivateJobsResponse struct {
	Jobs                 []*ActivatedJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActivateJobsResponse) Reset()         { *m = ActivateJobsResponse{} }
func (m *ActivateJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateJobsResponse) ProtoMessage()    {}
func (*ActivateJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{31}
}

func (m *ActivateJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateJobsResponse.Unmarshal(m, b)
}
func (m *ActivateJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateJobsResponse.Marshal(b, m, deterministic)
}
func (m *ActivateJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateJobsResponse.Merge(m, src)
}
func (m *ActivateJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateJobsResponse.Size(m)
}
func (m *ActivateJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateJobsResponse proto.InternalMessageInfo

func (m *ActivateJobsResponse) GetJobs() []*ActivatedJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterEnum("gateway_protocol.Partition_PartitionBrokerRole", Partition_PartitionBrokerRole_name, Partition_PartitionBrokerRole_value)
	proto.RegisterEnum("gateway_protocol.WorkflowRequestObject_ResourceType", WorkflowRequestObject_ResourceType_name, WorkflowRequestObject_ResourceType_value)
	proto.RegisterType((*TopologyRequest)(nil), "gateway_protocol.TopologyRequest")
	proto.RegisterType((*Partition)(nil), "gateway_protocol.Partition")
	proto.RegisterType((*BrokerInfo)(nil), "gateway_protocol.BrokerInfo")
	proto.RegisterType((*TopologyResponse)(nil), "gateway_protocol.TopologyResponse")
	proto.RegisterType((*WorkflowRequestObject)(nil), "gateway_protocol.WorkflowRequestObject")
	proto.RegisterType((*DeployWorkflowRequest)(nil), "gateway_protocol.DeployWorkflowRequest")
	proto.RegisterType((*WorkflowMetadata)(nil), "gateway_protocol.WorkflowMetadata")
	proto.RegisterType((*DeployWorkflowResponse)(nil), "gateway_protocol.DeployWorkflowResponse")
	proto.RegisterType((*PublishMessageRequest)(nil), "gateway_protocol.PublishMessageRequest")
	proto.RegisterType((*PublishMessageResponse)(nil), "gateway_protocol.PublishMessageResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "gateway_protocol.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "gateway_protocol.CreateJobResponse")
	proto.RegisterType((*UpdateJobRetriesRequest)(nil), "gateway_protocol.UpdateJobRetriesRequest")
	proto.RegisterType((*UpdateJobRetriesResponse)(nil), "gateway_protocol.UpdateJobRetriesResponse")
	proto.RegisterType((*FailJobRequest)(nil), "gateway_protocol.FailJobRequest")
	proto.RegisterType((*FailJobResponse)(nil), "gateway_protocol.FailJobResponse")
	proto.RegisterType((*CompleteJobRequest)(nil), "gateway_protocol.CompleteJobRequest")
	proto.RegisterType((*CompleteJobResponse)(nil), "gateway_protocol.CompleteJobResponse")
	proto.RegisterType((*CreateWorkflowInstanceRequest)(nil), "gateway_protocol.CreateWorkflowInstanceRequest")
	proto.RegisterType((*CreateWorkflowInstanceResponse)(nil), "gateway_protocol.CreateWorkflowInstanceResponse")
	proto.RegisterType((*CancelWorkflowInstanceRequest)(nil), "gateway_protocol.CancelWorkflowInstanceRequest")
	proto.RegisterType((*CancelWorkflowInstanceResponse)(nil), "gateway_protocol.CancelWorkflowInstanceResponse")
	proto.RegisterType((*UpdateWorkflowInstancePayloadRequest)(nil), "gateway_protocol.UpdateWorkflowInstancePayloadRequest")
	proto.RegisterType((*UpdateWorkflowInstancePayloadResponse)(nil), "gateway_protocol.UpdateWorkflowInstancePayloadResponse")
	proto.RegisterType((*ListWorkflowsRequest)(nil), "gateway_protocol.ListWorkflowsRequest")
	proto.RegisterType((*ListWorkflowsResponse)(nil), "gateway_protocol.ListWorkflowsResponse")
	proto.RegisterType((*GetWorkflowRequest)(nil), "gateway_protocol.GetWorkflowRequest")
	proto.RegisterType((*GetWorkflowResponse)(nil), "gateway_protocol.GetWorkflowResponse")
	proto.RegisterType((*ActivateJobsRequest)(nil), "gateway_protocol.ActivateJobsRequest")
	proto.RegisterType((*JobHeaders)(nil), "gateway_protocol.JobHeaders")
	proto.RegisterType((*ActivatedJob)(nil), "gateway_protocol.ActivatedJob")
	proto.RegisterType((*ActivateJobsResponse)(nil), "gateway_protocol.ActivateJobsResponse")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 1430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xfa, 0x5f, 0xe2, 0xd7, 0x34, 0x75, 0x26, 0x4d, 0xd8, 0x9a, 0x36, 0x72, 0x97, 0xa6,
	0x0d, 0xa8, 0x72, 0xab, 0x80, 0xca, 0x81, 0x1e, 0xda, 0xa4, 0x49, 0x9b, 0xd4, 0x69, 0xcd, 0xb6,
	0xb4, 0x14, 0x21, 0xd0, 0xee, 0x7a, 0x9a, 0x6e, 0xb2, 0xde, 0x59, 0x76, 0xd7, 0x89, 0x5c, 0x09,
	0x89, 0x13, 0x12, 0x47, 0x7a, 0x42, 0xe2, 0xc8, 0x91, 0x2b, 0x7c, 0x02, 0xf8, 0x12, 0x7c, 0x1b,
	0x34, 0xb3, 0x33, 0xeb, 0xfd, 0x33, 0x6b, 0x3b, 0x42, 0xdc, 0x66, 0xde, 0xbe, 0x79, 0x7f, 0x7e,
	0xef, 0xcd, 0xbc, 0x9f, 0x0d, 0xe7, 0x0f, 0x8d, 0x10, 0x9f, 0x1a, 0xa3, 0x8e, 0xe7, 0x93, 0x90,
	0xa0, 0x26, 0xdf, 0x7e, 0xcb, 0xb6, 0x16, 0x71, 0xb4, 0x25, 0xb8, 0xf0, 0x9c, 0x78, 0xc4, 0x21,
	0x87, 0x23, 0x1d, 0x7f, 0x37, 0xc4, 0x41, 0xa8, 0xfd, 0xa6, 0x40, 0xa3, 0x67, 0xf8, 0xa1, 0x1d,
	0xda, 0xc4, 0x45, 0x6d, 0x38, 0xe7, 0x89, 0xcd, 0x5e, 0x5f, 0x55, 0xda, 0xca, 0x46, 0x4d, 0x4f,
	0x8a, 0xd0, 0x36, 0x54, 0x7d, 0xe2, 0x60, 0xb5, 0xd2, 0x56, 0x36, 0x16, 0x37, 0x6f, 0x75, 0xb2,
	0x3e, 0x3a, 0xb1, 0xb1, 0xf1, 0x6a, 0xcb, 0x27, 0xc7, 0xd8, 0xd7, 0x89, 0x83, 0x75, 0x76, 0x58,
	0xbb, 0x05, 0xcb, 0x92, 0x8f, 0x08, 0xa0, 0xde, 0xdd, 0xb9, 0xff, 0x60, 0x47, 0x6f, 0x96, 0xd0,
	0x02, 0xcc, 0xef, 0x3e, 0xed, 0x76, 0x9f, 0xbe, 0xdc, 0xd1, 0x9b, 0x8a, 0xf6, 0x93, 0x02, 0x10,
	0x29, 0xee, 0xb9, 0xaf, 0x09, 0x5a, 0x85, 0xba, 0x4b, 0xfa, 0x38, 0x8e, 0x90, 0xef, 0x10, 0x82,
	0xea, 0x1b, 0x12, 0x84, 0x6a, 0xb9, 0xad, 0x6c, 0x34, 0x74, 0xb6, 0xa6, 0x32, 0x8f, 0xf8, 0x21,
	0x0b, 0xb8, 0xa6, 0xb3, 0x35, 0xfa, 0x0c, 0x20, 0xce, 0x29, 0x50, 0xab, 0xed, 0xca, 0xc6, 0xb9,
	0xcd, 0xf7, 0x27, 0xa4, 0xa2, 0x27, 0xd4, 0xb5, 0xbf, 0x15, 0x68, 0x8e, 0x51, 0x0c, 0x3c, 0xe2,
	0x06, 0x18, 0xdd, 0x81, 0x39, 0x93, 0xc5, 0x17, 0xa8, 0x0a, 0x33, 0x77, 0x39, 0x6f, 0x6e, 0x9c,
	0x80, 0x2e, 0x94, 0x29, 0xe0, 0x96, 0x33, 0x0c, 0x42, 0xec, 0x3f, 0xb3, 0xdf, 0x62, 0x16, 0x78,
	0x4d, 0x4f, 0x8a, 0xd0, 0x06, 0x5c, 0x18, 0x3b, 0xdf, 0x26, 0x43, 0x57, 0xa4, 0x92, 0x15, 0xa3,
	0x9b, 0xb0, 0xe4, 0x63, 0xcf, 0xb1, 0x2d, 0x83, 0x0a, 0x77, 0x0d, 0x2b, 0x24, 0xbe, 0x5a, 0x65,
	0xba, 0xf9, 0x0f, 0xda, 0x5f, 0x0a, 0xac, 0xbc, 0x24, 0xfe, 0xf1, 0x6b, 0x87, 0x9c, 0xf2, 0x66,
	0x78, 0x6a, 0x1e, 0x61, 0x8b, 0x21, 0xe6, 0x1a, 0x03, 0xcc, 0xb0, 0x6d, 0xe8, 0x6c, 0x8d, 0x1e,
	0x41, 0x35, 0x1c, 0x79, 0x51, 0x80, 0x8b, 0x9b, 0x9f, 0xe4, 0x93, 0x93, 0x9a, 0xea, 0xe8, 0x38,
	0x20, 0x43, 0xdf, 0xc2, 0xcf, 0x47, 0x1e, 0xd6, 0x99, 0x05, 0xb4, 0x06, 0xd0, 0xc7, 0xaf, 0x6d,
	0x97, 0x45, 0xce, 0x52, 0x59, 0xd0, 0x13, 0x12, 0xed, 0x26, 0x2c, 0x24, 0x4f, 0xa1, 0x79, 0xa8,
	0xee, 0xee, 0x75, 0x77, 0x9a, 0x25, 0xba, 0xda, 0xea, 0x1d, 0x3c, 0x69, 0x2a, 0x74, 0xf5, 0xea,
	0xfe, 0x41, 0xb7, 0x59, 0xd6, 0xbe, 0x81, 0x95, 0x07, 0xd8, 0x73, 0xc8, 0x28, 0xe3, 0x1f, 0xed,
	0x40, 0xe3, 0x94, 0x8b, 0x44, 0x49, 0x6e, 0xcc, 0x18, 0xb5, 0x3e, 0x3e, 0xa9, 0xfd, 0xa2, 0x40,
	0x53, 0x28, 0x1d, 0xe0, 0xd0, 0xe8, 0x1b, 0xa1, 0x81, 0xae, 0xc1, 0x79, 0xd3, 0x1b, 0xb8, 0x3d,
	0x9f, 0x58, 0x38, 0x08, 0x78, 0x17, 0x36, 0xf4, 0xb4, 0x10, 0xa9, 0x30, 0x77, 0x82, 0xfd, 0x80,
	0x66, 0x19, 0x95, 0x55, 0x6c, 0x69, 0xd1, 0x85, 0x87, 0xc7, 0x78, 0xc4, 0x30, 0xa8, 0xe8, 0x49,
	0x11, 0xd2, 0x60, 0xc1, 0xe7, 0x20, 0x3c, 0xa1, 0xa5, 0xa8, 0x32, 0x07, 0x29, 0x99, 0xe6, 0xc0,
	0x6a, 0x36, 0x75, 0xde, 0x8c, 0x4d, 0xa8, 0x1c, 0xe3, 0x11, 0x8b, 0xaa, 0xa2, 0xd3, 0x25, 0xba,
	0x97, 0x44, 0xa3, 0xcc, 0xd0, 0xd0, 0x8a, 0xd1, 0x10, 0x89, 0x26, 0x81, 0xf8, 0x5d, 0x81, 0x95,
	0xde, 0xd0, 0x74, 0xec, 0xe0, 0xcd, 0x01, 0x0e, 0x02, 0xe3, 0x10, 0x0b, 0xa4, 0x65, 0xed, 0x72,
	0x1d, 0x16, 0x2d, 0xe2, 0xfb, 0xd8, 0x61, 0x1d, 0x47, 0x93, 0x8c, 0xae, 0x64, 0x46, 0x4a, 0x9b,
	0x21, 0xb4, 0x07, 0xf8, 0x39, 0xe9, 0xda, 0x27, 0x98, 0x03, 0x91, 0x90, 0xa0, 0xcb, 0xd0, 0x18,
	0x44, 0xde, 0xf6, 0xfa, 0x1c, 0x84, 0xb1, 0x80, 0x22, 0xec, 0x19, 0x23, 0x87, 0x18, 0x7d, 0xb5,
	0xc6, 0xbe, 0x89, 0xad, 0xa6, 0xc2, 0x6a, 0x36, 0xd8, 0x08, 0x1b, 0xed, 0x47, 0x05, 0x9a, 0xdb,
	0x3e, 0x36, 0x42, 0xbc, 0x4f, 0x4c, 0x91, 0x82, 0x0a, 0x73, 0x47, 0xc4, 0xa4, 0xed, 0xc6, 0xb3,
	0x10, 0x5b, 0xfa, 0xc5, 0xc7, 0xa1, 0x6f, 0xe3, 0x40, 0x14, 0x91, 0x6f, 0x69, 0x13, 0x58, 0xc3,
	0x20, 0x24, 0x83, 0x47, 0xd8, 0xe8, 0xd3, 0x7b, 0x5f, 0x89, 0x9a, 0x20, 0x25, 0x4c, 0x86, 0x58,
	0x4d, 0x87, 0xb8, 0x0e, 0x4b, 0x89, 0x38, 0x8a, 0x2a, 0xa7, 0x3d, 0x86, 0xf7, 0xbe, 0xf0, 0xfa,
	0x42, 0x8d, 0xb9, 0x16, 0x51, 0xaf, 0x42, 0xfd, 0x88, 0x98, 0x8f, 0x63, 0x7d, 0xbe, 0x2b, 0x8e,
	0x59, 0x6b, 0x81, 0x9a, 0x37, 0xc6, 0x81, 0xd9, 0x82, 0xc5, 0x5d, 0xc3, 0x76, 0x12, 0xa8, 0x9c,
	0xdd, 0xfe, 0x12, 0x5c, 0x88, 0x6d, 0x70, 0xb3, 0xbb, 0x80, 0xb6, 0xc9, 0xc0, 0x73, 0x70, 0x0a,
	0xf0, 0x09, 0xa6, 0x05, 0x5c, 0xe5, 0x34, 0x5c, 0x2b, 0xb0, 0x9c, 0xb2, 0xc3, 0xcd, 0xff, 0xaa,
	0xc0, 0x95, 0x08, 0x46, 0xd1, 0xbc, 0x7b, 0x6e, 0x10, 0x1a, 0xae, 0x15, 0xb7, 0x67, 0xe6, 0xb2,
	0x29, 0xf9, 0xcb, 0x96, 0xbb, 0xce, 0xe5, 0x29, 0xd7, 0xb9, 0x92, 0xbe, 0xce, 0xc5, 0x35, 0xfe,
	0x43, 0x81, 0xb5, 0xa2, 0xe8, 0x78, 0xc5, 0xff, 0xff, 0xf0, 0x6e, 0xc3, 0xf2, 0x69, 0xc6, 0x3b,
	0xf5, 0x54, 0x63, 0x9e, 0x64, 0x9f, 0xb4, 0xcf, 0xe1, 0xca, 0x36, 0x5d, 0x3b, 0x45, 0x98, 0x16,
	0x98, 0x54, 0x8a, 0x4d, 0xb6, 0x61, 0xad, 0xc8, 0x24, 0xaf, 0xa4, 0x07, 0xd7, 0xa2, 0xde, 0xcc,
	0x6a, 0xf4, 0x22, 0x30, 0x85, 0xef, 0x0e, 0x20, 0xec, 0xe0, 0x01, 0x76, 0xc3, 0xbc, 0x6b, 0xc9,
	0x97, 0x09, 0x2d, 0x75, 0x03, 0xd6, 0xa7, 0x78, 0xe4, 0xa1, 0xdd, 0x85, 0x8b, 0x5d, 0x3b, 0x08,
	0x85, 0x5a, 0x7c, 0x01, 0x67, 0x9a, 0x03, 0xda, 0x2b, 0x58, 0xc9, 0x9c, 0xe6, 0xa5, 0xbf, 0x97,
	0x1f, 0x51, 0x67, 0x7c, 0x94, 0x4f, 0x00, 0x3d, 0xc4, 0x61, 0x76, 0xf4, 0x4d, 0x6f, 0xa9, 0xe2,
	0xd1, 0x94, 0x4b, 0xa9, 0x22, 0x4b, 0xe9, 0x4f, 0x05, 0x96, 0x53, 0x8e, 0x67, 0x6e, 0xe6, 0xff,
	0xe8, 0x79, 0x96, 0xc1, 0x48, 0x7d, 0xd0, 0x43, 0x5f, 0x0e, 0x1c, 0x31, 0x16, 0xf8, 0x56, 0xfb,
	0x59, 0x81, 0xe5, 0xfb, 0x56, 0x68, 0x9f, 0x44, 0x4f, 0x60, 0x90, 0x18, 0x61, 0xe1, 0xf8, 0xf1,
	0x8f, 0x78, 0xca, 0x2a, 0xd4, 0x69, 0xe0, 0xd8, 0xe7, 0x6d, 0xc3, 0x77, 0xd4, 0x3a, 0x1d, 0x50,
	0x64, 0x18, 0xf2, 0x79, 0x25, 0xb6, 0xf4, 0x84, 0x31, 0x60, 0x04, 0x2d, 0x22, 0x5d, 0x7c, 0x47,
	0x87, 0xd8, 0x89, 0xe1, 0xdb, 0x86, 0xe9, 0xe0, 0x40, 0xad, 0xb5, 0x2b, 0x74, 0x88, 0xc5, 0x02,
	0xed, 0x5d, 0x19, 0x60, 0x9f, 0x98, 0x62, 0x60, 0x9c, 0xf9, 0x6a, 0xcd, 0xf8, 0x3e, 0xdc, 0x85,
	0x4b, 0xe2, 0xf0, 0x83, 0x98, 0x6c, 0xbd, 0x48, 0xbd, 0x18, 0xc5, 0x0a, 0xd9, 0xc2, 0x56, 0xf3,
	0x85, 0xbd, 0x0c, 0x0d, 0x71, 0xf9, 0xc4, 0x34, 0x1e, 0x0b, 0x0a, 0x2e, 0x6d, 0xbd, 0xe8, 0xd2,
	0x6a, 0x3f, 0x94, 0x61, 0x41, 0x14, 0xaa, 0xbf, 0x4f, 0x4c, 0x09, 0xa5, 0x41, 0x09, 0x46, 0x2a,
	0x6a, 0x76, 0x17, 0xe0, 0x28, 0x86, 0x92, 0x65, 0x25, 0x25, 0xe2, 0x63, 0xb8, 0xf5, 0x84, 0x7e,
	0x7e, 0xa2, 0x57, 0x65, 0x13, 0x7d, 0xdc, 0x17, 0xb5, 0x6c, 0x5f, 0x88, 0xa9, 0x58, 0x4f, 0x33,
	0x85, 0x16, 0xcc, 0xf7, 0xb1, 0xd1, 0x77, 0x6c, 0x17, 0xab, 0x73, 0x2c, 0x81, 0x78, 0x9f, 0x7c,
	0x9d, 0xe6, 0xd3, 0xaf, 0xd3, 0x3e, 0x5c, 0x4c, 0xb7, 0x2a, 0xbf, 0x63, 0x9b, 0x50, 0x3d, 0x22,
	0xa6, 0x78, 0x30, 0xd6, 0xf2, 0xd9, 0x25, 0x71, 0xd3, 0x99, 0xee, 0xe6, 0x3f, 0x00, 0x73, 0x0f,
	0x23, 0x3d, 0xf4, 0x0c, 0xe6, 0xc5, 0xaf, 0x17, 0x74, 0x35, 0x7f, 0x3a, 0xf3, 0xfb, 0xb0, 0xa5,
	0x4d, 0x52, 0xe1, 0xef, 0x63, 0x09, 0x61, 0x58, 0x4c, 0x73, 0x51, 0x24, 0x21, 0xdb, 0x52, 0xa2,
	0xde, 0xda, 0x98, 0xae, 0x98, 0x74, 0x93, 0xa6, 0x75, 0x32, 0x37, 0x52, 0x96, 0x2a, 0x73, 0x53,
	0xc0, 0x10, 0x4b, 0xe8, 0x05, 0x34, 0x62, 0x6a, 0x86, 0x24, 0x00, 0x64, 0xf9, 0x63, 0xeb, 0x83,
	0x89, 0x3a, 0xb1, 0xdd, 0x63, 0x68, 0x66, 0xe9, 0x17, 0xfa, 0x30, 0x7f, 0xb4, 0x80, 0xef, 0xb5,
	0x3e, 0x9a, 0x45, 0x35, 0x76, 0xd6, 0x83, 0x39, 0xce, 0xc5, 0x50, 0x3b, 0x7f, 0x30, 0x4d, 0xf5,
	0x5a, 0x57, 0x27, 0x68, 0xc4, 0x16, 0xbf, 0x86, 0x73, 0x09, 0x0a, 0x86, 0xae, 0x49, 0x92, 0xce,
	0x31, 0xbd, 0xd6, 0xfa, 0x14, 0xad, 0xd8, 0xfa, 0xf7, 0xb0, 0x2a, 0xa7, 0x4a, 0xe8, 0x56, 0x11,
	0xba, 0x05, 0xf4, 0xa4, 0x75, 0x7b, 0xf6, 0x03, 0x29, 0xf7, 0x52, 0x82, 0x22, 0x75, 0x3f, 0x89,
	0x1d, 0x49, 0xdd, 0x4f, 0xe6, 0x3e, 0x25, 0xf4, 0x4e, 0x81, 0x2b, 0x13, 0xc9, 0x08, 0xba, 0x53,
	0x54, 0xfd, 0xc9, 0x7c, 0xa9, 0xf5, 0xe9, 0x99, 0xcf, 0xc5, 0x41, 0x19, 0xe3, 0x47, 0x98, 0x3e,
	0x41, 0x68, 0xbd, 0xf8, 0xb1, 0x49, 0x4c, 0xd3, 0xd6, 0xf5, 0x69, 0x6a, 0xc2, 0xc1, 0x6d, 0x05,
	0x99, 0x70, 0x3e, 0x45, 0x8e, 0x90, 0xe4, 0xb0, 0x8c, 0x7b, 0xb5, 0x6e, 0x4c, 0xd5, 0x4b, 0xf6,
	0x6d, 0x82, 0xac, 0xc8, 0xfa, 0x36, 0x4f, 0xa2, 0x64, 0x7d, 0x2b, 0x61, 0x3c, 0x5a, 0x69, 0xeb,
	0x2a, 0x5c, 0xb2, 0x49, 0xe7, 0x2d, 0xc6, 0x26, 0xee, 0xa4, 0xfe, 0x7f, 0xb3, 0x88, 0xd3, 0x2b,
	0x7d, 0x55, 0xf6, 0x4c, 0xb3, 0xce, 0xf6, 0x1f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x63, 0xe6,
	0xe3, 0xa0, 0xa0, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	Topology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyResponse, error)
	DeployWorkflow(ctx context.Context, in *DeployWorkflowRequest, opts ...grpc.CallOption) (*DeployWorkflowResponse, error)
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	UpdateJobRetries(ctx context.Context, in *UpdateJobRetriesRequest, opts ...grpc.CallOption) (*UpdateJobRetriesResponse, error)
	FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error)
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
	CreateWorkflowInstance(ctx context.Context, in *CreateWorkflowInstanceRequest, opts ...grpc.CallOption) (*CreateWorkflowInstanceResponse, error)
	CancelWorkflowInstance(ctx context.Context, in *CancelWorkflowInstanceRequest, opts ...grpc.CallOption) (*CancelWorkflowInstanceResponse, error)
	UpdateWorkflowInstancePayload(ctx context.Context, in *UpdateWorkflowInstancePayloadRequest, opts ...grpc.CallOption) (*UpdateWorkflowInstancePayloadResponse, error)
	ActivateJobs(ctx context.Context, in *ActivateJobsRequest, opts ...grpc.CallOption) (Gateway_ActivateJobsClient, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*GetWorkflowResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Topology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyResponse, error) {
	out := new(TopologyResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/Topology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) DeployWorkflow(ctx context.Context, in *DeployWorkflowRequest, opts ...grpc.CallOption) (*DeployWorkflowResponse, error) {
	out := new(DeployWorkflowResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/DeployWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/PublishMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateJobRetries(ctx context.Context, in *UpdateJobRetriesRequest, opts ...grpc.CallOption) (*UpdateJobRetriesResponse, error) {
	out := new(UpdateJobRetriesResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/UpdateJobRetries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error) {
	out := new(FailJobResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/FailJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CompleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateWorkflowInstance(ctx context.Context, in *CreateWorkflowInstanceRequest, opts ...grpc.CallOption) (*CreateWorkflowInstanceResponse, error) {
	out := new(CreateWorkflowInstanceResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CreateWorkflowInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CancelWorkflowInstance(ctx context.Context, in *CancelWorkflowInstanceRequest, opts ...grpc.CallOption) (*CancelWorkflowInstanceResponse, error) {
	out := new(CancelWorkflowInstanceResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CancelWorkflowInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateWorkflowInstancePayload(ctx context.Context, in *UpdateWorkflowInstancePayloadRequest, opts ...grpc.CallOption) (*UpdateWorkflowInstancePayloadResponse, error) {
	out := new(UpdateWorkflowInstancePayloadResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/UpdateWorkflowInstancePayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ActivateJobs(ctx context.Context, in *ActivateJobsRequest, opts ...grpc.CallOption) (Gateway_ActivateJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gateway_serviceDesc.Streams[0], "/gateway_protocol.Gateway/ActivateJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayActivateJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gateway_ActivateJobsClient interface {
	Recv() (*ActivateJobsResponse, error)
	grpc.ClientStream
}

type gatewayActivateJobsClient struct {
	grpc.ClientStream
}

func (x *gatewayActivateJobsClient) Recv() (*ActivateJobsResponse, error) {
	m := new(ActivateJobsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gatewayClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/ListWorkflows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*GetWorkflowResponse, error) {
	out := new(GetWorkflowResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/GetWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	Topology(context.Context, *TopologyRequest) (*TopologyResponse, error)
	DeployWorkflow(context.Context, *DeployWorkflowRequest) (*DeployWorkflowResponse, error)
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	UpdateJobRetries(context.Context, *UpdateJobRetriesRequest) (*UpdateJobRetriesResponse, error)
	FailJob(context.Context, *FailJobRequest) (*FailJobResponse, error)
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	CreateWorkflowInstance(context.Context, *CreateWorkflowInstanceRequest) (*CreateWorkflowInstanceResponse, error)
	CancelWorkflowInstance(context.Context, *CancelWorkflowInstanceRequest) (*CancelWorkflowInstanceResponse, error)
	UpdateWorkflowInstancePayload(context.Context, *UpdateWorkflowInstancePayloadRequest) (*UpdateWorkflowInstancePayloadResponse, error)
	ActivateJobs(*ActivateJobsRequest, Gateway_ActivateJobsServer) error
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*GetWorkflowResponse, error)
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Topology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Topology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/Topology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Topology(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_DeployWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).DeployWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/DeployWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).DeployWorkflow(ctx, req.(*DeployWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/PublishMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateJobRetries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRetriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateJobRetries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/UpdateJobRetries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateJobRetries(ctx, req.(*UpdateJobRetriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_FailJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).FailJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/FailJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).FailJob(ctx, req.(*FailJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CompleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateWorkflowInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateWorkflowInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CreateWorkflowInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateWorkflowInstance(ctx, req.(*CreateWorkflowInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CancelWorkflowInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CancelWorkflowInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CancelWorkflowInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CancelWorkflowInstance(ctx, req.(*CancelWorkflowInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateWorkflowInstancePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowInstancePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateWorkflowInstancePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/UpdateWorkflowInstancePayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateWorkflowInstancePayload(ctx, req.(*UpdateWorkflowInstancePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ActivateJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActivateJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServer).ActivateJobs(m, &gatewayActivateJobsServer{stream})
}

type Gateway_ActivateJobsServer interface {
	Send(*ActivateJobsResponse) error
	grpc.ServerStream
}

type gatewayActivateJobsServer struct {
	grpc.ServerStream
}

func (x *gatewayActivateJobsServer) Send(m *ActivateJobsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Gateway_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/ListWorkflows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/GetWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway_protocol.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Topology",
			Handler:    _Gateway_Topology_Handler,
		},
		{
			MethodName: "DeployWorkflow",
			Handler:    _Gateway_DeployWorkflow_Handler,
		},
		{
			MethodName: "PublishMessage",
			Handler:    _Gateway_PublishMessage_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _Gateway_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJobRetries",
			Handler:    _Gateway_UpdateJobRetries_Handler,
		},
		{
			MethodName: "FailJob",
			Handler:    _Gateway_FailJob_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _Gateway_CompleteJob_Handler,
		},
		{
			MethodName: "CreateWorkflowInstance",
			Handler:    _Gateway_CreateWorkflowInstance_Handler,
		},
		{
			MethodName: "CancelWorkflowInstance",
			Handler:    _Gateway_CancelWorkflowInstance_Handler,
		},
		{
			MethodName: "UpdateWorkflowInstancePayload",
			Handler:    _Gateway_UpdateWorkflowInstancePayload_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _Gateway_ListWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _Gateway_GetWorkflow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ActivateJobs",
			Handler:       _Gateway_ActivateJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
